name: soil_health_monitor
description: A Flutter app for monitoring soil health via Bluetooth devices

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  
  # State Management
  provider: ^6.0.5
  
  # Bluetooth
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.2.0
  
  # UI & Charts
  fl_chart: ^0.62.0
  intl: ^0.18.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true